### PR TITLE
feat(Date Types): add EncryptedDateField, and EncryptedNaiveDatetimeF…

### PR DESCRIPTION
**Pull request by tomciopp**
…ield

This PR adds two types for Date fields. The code and tests should be fairly standard. Let me know if you have any questions.

### CODE REVIEW

**Comment by danielberkompas** [comment]
These look good! Any reason why there isn't an `EncryptedDateTime` field? Is it more difficult?

**Comment by tomciopp** [comment]
These are both extracted from a production application, I've not needed an `EncryptedDateTime`, so I've not written it. Also now that you've commented here, I've just checked and I need to fix the module name so it matches elixir's conventions. `NaiveDatetime` => `NaiveDateTime`. Will patch.

**Comment by tomciopp** [comment]
Updated to fix typo and code formatting.

**Comment by danielberkompas** [comment]
⭐️ 🌟 ⭐️

**Pull request merged**
